### ISSUE TITLE
KEY_ NOT_SET

### ISSUE THREAD

**Issue by pazDontExist** [skokov3812/encrypted-smiley-secure-protocol#39]
Hi, first of all thank you for this amazing project. 

I have a bit of a problem: all the command return 
`{ success: false,
  status: 'KEY_NOT_SET',
  command: 'ENABLE',
  info: {} }
`

the hardware is an NV9USB and here the config of the lib:
`let eSSP = new sspLib({
    id: 0,
    debug: true,
    timeout: 50000,
    encryptAllCommand: true,
    fixedKey: '0123456701234567'
});
`

Thank you for your time

**Comment by kybarg** [comment]
@pazDontExist have you tried to run example script?
Do you run commands prior to `ENABLE` command?

**Comment by pazDontExist** [comment]
the example script goes on timeout with host protocol version, the only command working appear to be only sync

**Comment by pazDontExist** [comment]
nv9usb

**Comment by kybarg** [comment]
@pazDontExist would be nice if you could run example script with debug unabled and provide output.

**Comment by pazDontExist** [comment]
`C:\Users\misfo\Downloads\encrypted-smiley-secure-protocol-master\encrypted-smiley-secure-protocol-master>node example.js
Port opened!
COM <- 7f0001116608 null 0
COM -> 7f0001f0200a SYNC
{ success: true, status: 'OK', command: 'SYNC', info: {} }
COM <- 7f000206061b94 SYNC 0
COM -> 7f0001f43b8a HOST_PROTOCOL_VERSION
{
  success: false,
  status: 'PARAMETER_OUT_OF_RANGE',
  command: 'HOST_PROTOCOL_VERSION',
  info: {}
}
COM <- 7f80094a13fa000000000000afc2 HOST_PROTOCOL_VERSION 0
COM -> 7f8001f02380 SET_GENERATOR
{ success: true, status: 'OK', command: 'SET_GENERATOR', info: {} }
COM <- 7f00094bc3ef0000000000006d72 SET_GENERATOR 0
COM -> 7f0001f0200a SET_MODULUS
{ success: true, status: 'OK', command: 'SET_MODULUS', info: {} }
COM <- 7f80094c129d0000000000009a26 SET_MODULUS 0
COM -> 7f8009f06675000000000000ba31 REQUEST_KEY_EXCHANGE
{
  success: true,
  status: 'OK',
  command: 'REQUEST_KEY_EXCHANGE',
  info: { key: [
      102, 117, 0, 0,
        0,   0, 0, 0
    ] }
}
AES encrypt key: 0x674523016745230115d5000000000000

{
  fixedKey: '0123456701234567',
  generatorKey: 64019n,
  modulusKey: 61379n,
  hostRandom: 33107n,
  hostIntKey: 40210n,
  slaveIntKey: 30054n,
  key: 54549n
}

COM -> 7f0001fa1c0a REQUEST_KEY_EXCHANGE
COM <- 7f00117efd01cec14ae81fcf6b2c363e63481a273f48 REQUEST_KEY_EXCHANGE 0
COM -> 7f8001f02380 GET_SERIAL_NUMBER
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at new NodeError (node:internal/errors:371:5)
    at boundsError (node:internal/buffer:84:11)
    at Buffer.readInt32BE (node:internal/buffer:482:5)
    at parseData (C:\Users\misfo\Downloads\encrypted-smiley-secure-protocol-master\encrypted-smiley-secure-protocol-master\src\utils.js:203:65)
    at SSP.parsePacket (C:\Users\misfo\Downloads\encrypted-smiley-secure-protocol-master\encrypted-smiley-secure-protocol-master\src\index.js:218:24)
    at EventEmitter.<anonymous> (C:\Users\misfo\Downloads\encrypted-smiley-secure-protocol-master\encrypted-smiley-secure-protocol-master\src\index.js:172:24)
    at Object.onceWrapper (node:events:510:26)
    at EventEmitter.emit (node:events:390:28)
    at ESSPProtocolParser.<anonymous> (C:\Users\misfo\Downloads\encrypted-smiley-secure-protocol-master\encrypted-smiley-secure-protocol-master\src\index.js:58:27)
    at ESSPProtocolParser.emit (node:events:390:28) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'`

**Comment by pazDontExist** [comment]
** without debug **
```bash
Port opened!
SERIAL NUMBER: undefined
GO!!!
```
and is not working...


**with debug**
```bash
Port opened!
COM <- 7f0001116608 null 0
COM -> 7f0001f0200a SYNC
{ success: true, status: 'OK', command: 'SYNC', info: {} }
COM <- 7f000206061b94 SYNC 0
COM -> 7f0001f43b8a HOST_PROTOCOL_VERSION
{
  success: false,
  status: 'PARAMETER_OUT_OF_RANGE',
  command: 'HOST_PROTOCOL_VERSION',
  info: {}
}
COM <- 7f80094aaba1000000000000b51f HOST_PROTOCOL_VERSION 0
COM -> 7f0001f43b8a SET_GENERATOR
{
  success: false,
  status: 'PARAMETER_OUT_OF_RANGE',
  command: 'SET_GENERATOR',
  info: {}
}
COM <- 7f00094bc3ef0000000000006d72 SET_GENERATOR 0
COM -> 7f0001f43b8a SET_MODULUS
{
  success: false,
  status: 'PARAMETER_OUT_OF_RANGE',
  command: 'SET_MODULUS',
  info: {}
}
COM <- 7f80094c4cc80000000000001097 SET_MODULUS 0
COM -> 7f8001f81000 REQUEST_KEY_EXCHANGE
{
  success: false,
  status: 'FAIL',
  command: 'REQUEST_KEY_EXCHANGE',
  info: {}
}
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at SSP.createHostEncryptionKeys (C:\Users\misfo\Downloads\encrypted-smiley-secure-protocol-master\encrypted-smiley-secure-protocol-master\src\index.js:240:38)
    at SSP.parsePacket (C:\Users\misfo\Downloads\encrypted-smiley-secure-protocol-master\encrypted-smiley-secure-protocol-master\src\index.js:225:14)
    at EventEmitter.<anonymous> (C:\Users\misfo\Downloads\encrypted-smiley-secure-protocol-master\encrypted-smiley-secure-protocol-master\src\index.js:172:24)
    at Object.onceWrapper (node:events:510:26)
    at EventEmitter.emit (node:events:390:28)
    at ESSPProtocolParser.<anonymous> (C:\Users\misfo\Downloads\encrypted-smiley-secure-protocol-master\encrypted-smiley-secure-protocol-master\src\index.js:58:27)
    at ESSPProtocolParser.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by kybarg** [comment]
@pazDontExist seems like you are trying to set protocol version `6` which is not supported by device. Try `5` or lower

**Comment by kybarg** [comment]
@pazDontExist alos you can try to run `Setup Request` right after sync command and find out protocl version, but do not forget to disable encryption

**Comment by pazDontExist** [comment]
nothing, after the sync command i run the setup request and it return **parameter_out_of_range** and all the other commands **key_not_set**

**Comment by kybarg** [comment]
@pazDontExist aslo forgot to ask, Are you using NPM version or ;atest comit from this repo?

**Comment by pazDontExist** [comment]
Latest commit of this repo

Il Ven 24 Dic 2021, 18:31 Ruslan Kyba ***@***.***> ha scritto:

**Comment by pazDontExist** [comment]
still stuck. after sync no matter what command i give the result is always the same: parameter out of range

**Comment by kybarg** [comment]
@pazDontExist try testing with different protocol versions lwoer then 6
```javascript
.then(() => eSSP.command('HOST_PROTOCOL_VERSION', { version: 6 }))
```

**Comment by pazDontExist** [comment]
already tried. from 1 to 8. always parameter out of range as response

**Comment by kybarg** [comment]
@pazDontExist ahve you found a solution?

**Comment by pazDontExist** [comment]
yes, hard reset of the device and node upgrade
