### ISSUE TITLE
ERR_BUFFER_OUT_OF _BOUNDS

### ISSUE THREAD

**Issue by pazDontExist** [skokov3812/encrypted-smiley-secure-protocol#40]
`COM -> 7f0009f06c9d0000000000003957 REQUEST_KEY_EXCHANGE

{ success: true,
  status: 'OK',
  command: 'REQUEST_KEY_EXCHANGE',
  info: { key: [ 108, 157, 0, 0, 0, 0, 0, 0 ] } }

(node:19451) UnhandledPromiseRejectionWarning: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:47:11)
    at Buffer.readBigInt64BE (internal/buffer.js:118:5)
    at SSP.createHostEncryptionKeys (/home/pi/encrypted-smiley-secure-protocol/src/index.js:243:56)
    at SSP.parsePacket (/home/pi/encrypted-smiley-secure-protocol/src/index.js:225:14)
    at EventEmitter.eventEmitter.once.buffer (/home/pi/encrypted-smiley-secure-protocol/src/index.js:172:24)
    at Object.onceWrapper (events.js:286:20)
    at EventEmitter.emit (events.js:198:13)
    at ESSPProtocolParser.parser.on.buffer (/home/pi/encrypted-smiley-secure-protocol/src/index.js:58:27)
    at ESSPProtocolParser.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
(node:19451) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19451) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by kybarg** [comment]
@pazDontExist what happens when you run commands without encryption?

**Comment by pazDontExist** [comment]
they dont work anyway. this error happens everytime you set a key with a len != 16
